version: "3.1"
services:
  mogboard:
    image: ghcr.io/universalis-ffxiv/mogboard-next:latest
    restart: always
    environment:
      APP_ENV: "prod"
      NEXTAUTH_URL: "https://universalis.app"

      DATABASE_HOST: "mariadb"
      DATABASE_PORT: "3306"
      DATABASE_USER: "dalamud"
      DATABASE_PASS: "dalamud"
      DATABASE_NAME: "dalamud"
      DATABASE_CONNECTIONS: "32"

      LODESTONE_API: "https://lodestone.universalis.app"

      DISCORD_CLIENT_ID: "${MOGBOARD_DISCORD_ID}"
      DISCORD_CLIENT_SECRET: "${MOGBOARD_DISCORD_SECRET}"
      NEXTAUTH_SECRET: "${MOGBOARD_SECRET}"
    depends_on:
      - mariadb
      - lodestone
    ports:
      - "7000:3000"
  mariadb:
    image: mariadb:10.3.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MOGBOARD_DB_SECRET}"
      MYSQL_DATABASE: "dalamud"
      MYSQL_USER: "dalamud"
      MYSQL_PASSWORD: "dalamud"
    volumes:
      - "${HOME}/mogboard-mariadb:/var/lib/mysql"
      - "${HOME}/mogboard-mariadb-dump:/dump"
      - "${HOME}/mogboard-mariadb-import:/import"
    ports:
      - "7001:3306"